print("     *  ")
print("    * *  ")
print("   * * *  ")
print("  * * * *  ")
print(" * * * * * ")
print(" * * * * *  ")
print("  * * * *  ")
print("   * * *  ")
print("    * *  ")
print("     *  ")
#hình2
print("         *    ")
print("        ***    ")
print("       *****   ")
print("      ******* ")
print("     ********* ")
print("    *********** ")
print("   ************* ")
print("        ***    ")
print("        ***    ")
print("        ***    ")